"""empty message

Revision ID: a40b04c825a8
Revises: 7edba2483aed
Create Date: 2017-12-14 16:16:58.374239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40b04c825a8'
down_revision = '7edba2483aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matches_direID', table_name='matches')
    op.drop_index('ix_matches_leagueID', table_name='matches')
    op.drop_index('ix_matches_radiantID', table_name='matches')
    op.drop_index('ix_player_heroes_hero', table_name='player_heroes')
    op.drop_index('ix_player_heroes_playerID', table_name='player_heroes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_heroes_playerID', 'player_heroes', ['playerID'], unique=False)
    op.create_index('ix_player_heroes_hero', 'player_heroes', ['hero'], unique=False)
    op.create_index('ix_matches_radiantID', 'matches', ['radiantID'], unique=False)
    op.create_index('ix_matches_leagueID', 'matches', ['leagueID'], unique=False)
    op.create_index('ix_matches_direID', 'matches', ['direID'], unique=False)
    # ### end Alembic commands ###
