"""empty message

Revision ID: ecbf36aa175d
Revises: 
Create Date: 2017-12-13 15:53:25.620262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbf36aa175d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('replayID', sa.Integer(), nullable=False),
    sa.Column('direID', sa.Integer(), nullable=True),
    sa.Column('radiantID', sa.Integer(), nullable=True),
    sa.Column('leagueID', sa.Integer(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('radiantWin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('replayID')
    )
    op.create_index(op.f('ix_matches_direID'), 'matches', ['direID'], unique=False)
    op.create_index(op.f('ix_matches_leagueID'), 'matches', ['leagueID'], unique=False)
    op.create_index(op.f('ix_matches_radiantID'), 'matches', ['radiantID'], unique=False)
    op.create_table('match_retrieval',
    sa.Column('replayID', sa.Integer(), nullable=False),
    sa.Column('clusterID', sa.Integer(), nullable=True),
    sa.Column('salt', sa.Integer(), nullable=True),
    sa.Column('downloadAttempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replayID'], ['matches.replayID'], ),
    sa.PrimaryKeyConstraint('replayID')
    )
    op.create_table('player_heroes',
    sa.Column('replayID', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('Radiant', 'Dire', name='pnbteam'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=True),
    sa.Column('hero', sa.String(), nullable=True),
    sa.Column('idPick', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['replayID'], ['matches.replayID'], ),
    sa.PrimaryKeyConstraint('replayID', 'side', 'order')
    )
    op.create_index(op.f('ix_player_heroes_playerID'), 'player_heroes', ['playerID'], unique=False)
    op.create_index(op.f('ix_player_heroes_hero'), 'player_heroes', ['hero'], unique=False)
    op.drop_table('migrate_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.drop_index(op.f('ix_player_heroes_hero'), table_name='player_heroes')
    op.drop_index(op.f('ix_player_heroes_playerID'), table_name='player_heroes')
    op.drop_table('player_heroes')
    op.drop_table('match_retrieval')
    op.drop_index(op.f('ix_matches_radiantID'), table_name='matches')
    op.drop_index(op.f('ix_matches_leagueID'), table_name='matches')
    op.drop_index(op.f('ix_matches_direID'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
